//  Copyright 2020-2026 Herald Project Contributors
//  SPDX-License-Identifier: Apache-2.0
//

plugins {
    id 'maven-publish'
    id 'signing'
    id 'com.github.spotbugs' version '6.4.8'
    id 'org.jetbrains.kotlin.android'
}

group = 'io.heraldprox'
version = '2.3.0'

apply plugin: 'com.android.library'

android {
//    compileSdk 36
    compileSdk { version = release(36) }
    compileSdkVersion 36
//    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 23 // due to endoirdx.core:core:1.18.0 not supporting v21
        targetSdkVersion 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


    testOptions {
        unitTests.returnDefaultValues = true
//        targetSdk 36
//        targetSdk { version = release(36) }
    }
    namespace = 'io.heraldprox.herald'
    lint {
        disable 'ObsoleteLintCustomCheck'
        targetSdk = 36
    }
    buildFeatures {
        buildConfig = true
    }
    buildToolsVersion '36.0.0'
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation 'androidx.core:core-ktx:1.18.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.json:json:20251224"
    testImplementation project(path: ':herald')
    spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.14.0'
}

ext["signing.gnupg.passphrase"] = System.getenv('GPG_PASSPHRASE') 
ext["signing.gnupg.keyName"] = System.getenv('GPG_KEYID') 

signing {
    useGpgCmd()
    sign publishing.publications
}

afterEvaluate {
    publishing {
        /*publications {
            release(MavenPublication) {
                from components.release
                //artifact sourcesJar
                //artifact javadocJar

                groupId = 'io.heraldprox'
                artifactId = 'herald'
                pom {
                    name = 'Herald'
                    description = 'Reliable consumer device Bluetooth library'
                    url = 'https://heraldprox.io/'
                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                    developers {
                        developer {
                            id = 'adamfowleruk'
                            name = 'Adam Fowler'
                            email = 'adam@adamfowler.org'
                        }
                    }
                    scm {
                        connection = 'scm:git:git://github.com/theheraldproject/herald-for-android.git'
                        developerConnection = 'scm:git:ssh://github.com/theheraldproject/herald-for-android.git'
                        url = 'https://heraldprox.io/'
                    }
                }
            }
            debug(MavenPublication) {
                // Applies the component for the debug build variant.
                from components.debug
                //artifact sourcesJar
                //artifact javadocJar

                groupId = 'io.heraldprox'
                artifactId = 'herald-debug'
                pom {
                    name = 'Herald'
                    description = 'Reliable consumer device Bluetooth library'
                    url = 'https://heraldprox.io/'
                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                    developers {
                        developer {
                            id = 'adamfowleruk'
                            name = 'Adam Fowler'
                            email = 'adam@adamfowler.org'
                        }
                    }
                    scm {
                        connection = 'scm:git:git://github.com/theheraldproject/herald-for-android.git'
                        developerConnection = 'scm:git:ssh://github.com/theheraldproject/herald-for-android.git'
                        url = 'https://heraldprox.io/'
                    }
                }
            }
        }*/

        repositories {
            maven {
                name = "OSSRH"
                url = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                }
            }
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/theheraldproject/herald-for-android"
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

tasks.register('javadoc', Javadoc) {

    doFirst {
        configurations.implementation
                .filter { it.name.endsWith('.aar') }
                .each { aar ->
                    copy {
                        from zipTree(aar)
                        include "**/classes.jar"
                        into "${project.layout.buildDirectory}/tmp/aarsToJars/${aar.name.replace('.aar', '')}/"
                    }
                }
    }

    configurations.implementation.setCanBeResolved(true)
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    classpath += configurations.implementation
    classpath += fileTree(dir: "${project.layout.buildDirectory}/tmp/aarsToJars/")
    destinationDir = file("${project.layout.buildDirectory}/outputs/javadoc/")
    failOnError false
    exclude '**/BuildConfig.java'
    exclude '**/R.java'
}
