name: Publish to Maven and GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: [ubuntu-latest] 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.GPG_PUBLISH_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PUBLISH_PASSPHRASE }} 
          
      - name: Publish to the Maven Central Repository
        run: ./gradlew publish --stacktrace --info
        env: 
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PUBLISH_PASSPHRASE }}